# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status_reply.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'status_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12status_reply.proto\x12\x15\x61pplibs.appcore.proto\"C\n\nStatusItem\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nerror_flag\x18\x03 \x01(\x08\"a\n\tStatusKey\x12\x10\n\x08main_key\x18\x01 \x01(\t\x12\x0f\n\x07sub_key\x18\x02 \x01(\t\x12\x31\n\x06status\x18\x03 \x03(\x0b\x32!.applibs.appcore.proto.StatusItem\"E\n\x11StatusInformation\x12\x30\n\x06record\x18\x01 \x03(\x0b\x32 .applibs.appcore.proto.StatusKey')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSITEM']._serialized_start=45
  _globals['_STATUSITEM']._serialized_end=112
  _globals['_STATUSKEY']._serialized_start=114
  _globals['_STATUSKEY']._serialized_end=211
  _globals['_STATUSINFORMATION']._serialized_start=213
  _globals['_STATUSINFORMATION']._serialized_end=282
# @@protoc_insertion_point(module_scope)
