# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status_request.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'status_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14status_request.proto\x12\x15\x61pplibs.appcore.proto\"0\n\x07KeyPair\x12\x12\n\x08main_key\x18\x01 \x01(\t:\x00\x12\x11\n\x07sub_key\x18\x02 \x01(\t:\x00\"}\n\rStatusRequest\x12\x1b\n\x0bnum_records\x18\x01 \x01(\x05:\x06\x39\x39\x39\x39\x39\x39\x12!\n\x11time_length_milli\x18\x02 \x01(\x05:\x06\x39\x39\x39\x39\x39\x39\x12,\n\x04keys\x18\x03 \x03(\x0b\x32\x1e.applibs.appcore.proto.KeyPair')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYPAIR']._serialized_start=47
  _globals['_KEYPAIR']._serialized_end=95
  _globals['_STATUSREQUEST']._serialized_start=97
  _globals['_STATUSREQUEST']._serialized_end=222
# @@protoc_insertion_point(module_scope)
