// source: StatusRequest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.applibs.appcore.proto.KeyPair', null, global);
goog.exportSymbol('proto.applibs.appcore.proto.StatusRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.applibs.appcore.proto.KeyPair = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.applibs.appcore.proto.KeyPair, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.applibs.appcore.proto.KeyPair.displayName = 'proto.applibs.appcore.proto.KeyPair';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.applibs.appcore.proto.StatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.applibs.appcore.proto.StatusRequest.repeatedFields_, null);
};
goog.inherits(proto.applibs.appcore.proto.StatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.applibs.appcore.proto.StatusRequest.displayName = 'proto.applibs.appcore.proto.StatusRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.applibs.appcore.proto.KeyPair.prototype.toObject = function(opt_includeInstance) {
  return proto.applibs.appcore.proto.KeyPair.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.applibs.appcore.proto.KeyPair} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.KeyPair.toObject = function(includeInstance, msg) {
  var f, obj = {
    mainKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    subKey: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.applibs.appcore.proto.KeyPair}
 */
proto.applibs.appcore.proto.KeyPair.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.applibs.appcore.proto.KeyPair;
  return proto.applibs.appcore.proto.KeyPair.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.applibs.appcore.proto.KeyPair} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.applibs.appcore.proto.KeyPair}
 */
proto.applibs.appcore.proto.KeyPair.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.applibs.appcore.proto.KeyPair.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.applibs.appcore.proto.KeyPair.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.applibs.appcore.proto.KeyPair} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.KeyPair.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string main_key = 1;
 * @return {string}
 */
proto.applibs.appcore.proto.KeyPair.prototype.getMainKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.applibs.appcore.proto.KeyPair} returns this
 */
proto.applibs.appcore.proto.KeyPair.prototype.setMainKey = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.KeyPair} returns this
 */
proto.applibs.appcore.proto.KeyPair.prototype.clearMainKey = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.KeyPair.prototype.hasMainKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string sub_key = 2;
 * @return {string}
 */
proto.applibs.appcore.proto.KeyPair.prototype.getSubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.applibs.appcore.proto.KeyPair} returns this
 */
proto.applibs.appcore.proto.KeyPair.prototype.setSubKey = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.KeyPair} returns this
 */
proto.applibs.appcore.proto.KeyPair.prototype.clearSubKey = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.KeyPair.prototype.hasSubKey = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.applibs.appcore.proto.StatusRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.applibs.appcore.proto.StatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.applibs.appcore.proto.StatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    numRecords: jspb.Message.getFieldWithDefault(msg, 1, 999999),
    timeLengthMilli: jspb.Message.getFieldWithDefault(msg, 2, 999999),
    keysList: jspb.Message.toObjectList(msg.getKeysList(),
    proto.applibs.appcore.proto.KeyPair.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.applibs.appcore.proto.StatusRequest}
 */
proto.applibs.appcore.proto.StatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.applibs.appcore.proto.StatusRequest;
  return proto.applibs.appcore.proto.StatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.applibs.appcore.proto.StatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.applibs.appcore.proto.StatusRequest}
 */
proto.applibs.appcore.proto.StatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumRecords(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimeLengthMilli(value);
      break;
    case 3:
      var value = new proto.applibs.appcore.proto.KeyPair;
      reader.readMessage(value,proto.applibs.appcore.proto.KeyPair.deserializeBinaryFromReader);
      msg.addKeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.applibs.appcore.proto.StatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.applibs.appcore.proto.StatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getKeysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.applibs.appcore.proto.KeyPair.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 num_records = 1;
 * @return {number}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.getNumRecords = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 999999));
};


/**
 * @param {number} value
 * @return {!proto.applibs.appcore.proto.StatusRequest} returns this
 */
proto.applibs.appcore.proto.StatusRequest.prototype.setNumRecords = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusRequest} returns this
 */
proto.applibs.appcore.proto.StatusRequest.prototype.clearNumRecords = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.hasNumRecords = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 time_length_milli = 2;
 * @return {number}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.getTimeLengthMilli = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 999999));
};


/**
 * @param {number} value
 * @return {!proto.applibs.appcore.proto.StatusRequest} returns this
 */
proto.applibs.appcore.proto.StatusRequest.prototype.setTimeLengthMilli = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusRequest} returns this
 */
proto.applibs.appcore.proto.StatusRequest.prototype.clearTimeLengthMilli = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.hasTimeLengthMilli = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated KeyPair keys = 3;
 * @return {!Array<!proto.applibs.appcore.proto.KeyPair>}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.getKeysList = function() {
  return /** @type{!Array<!proto.applibs.appcore.proto.KeyPair>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.applibs.appcore.proto.KeyPair, 3));
};


/**
 * @param {!Array<!proto.applibs.appcore.proto.KeyPair>} value
 * @return {!proto.applibs.appcore.proto.StatusRequest} returns this
*/
proto.applibs.appcore.proto.StatusRequest.prototype.setKeysList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.applibs.appcore.proto.KeyPair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.applibs.appcore.proto.KeyPair}
 */
proto.applibs.appcore.proto.StatusRequest.prototype.addKeys = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.applibs.appcore.proto.KeyPair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.applibs.appcore.proto.StatusRequest} returns this
 */
proto.applibs.appcore.proto.StatusRequest.prototype.clearKeysList = function() {
  return this.setKeysList([]);
};


goog.object.extend(exports, proto.applibs.appcore.proto);
