// source: StatusReply.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.applibs.appcore.proto.StatusInformation', null, global);
goog.exportSymbol('proto.applibs.appcore.proto.StatusItem', null, global);
goog.exportSymbol('proto.applibs.appcore.proto.StatusKey', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.applibs.appcore.proto.StatusItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.applibs.appcore.proto.StatusItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.applibs.appcore.proto.StatusItem.displayName = 'proto.applibs.appcore.proto.StatusItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.applibs.appcore.proto.StatusKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.applibs.appcore.proto.StatusKey.repeatedFields_, null);
};
goog.inherits(proto.applibs.appcore.proto.StatusKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.applibs.appcore.proto.StatusKey.displayName = 'proto.applibs.appcore.proto.StatusKey';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.applibs.appcore.proto.StatusInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.applibs.appcore.proto.StatusInformation.repeatedFields_, null);
};
goog.inherits(proto.applibs.appcore.proto.StatusInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.applibs.appcore.proto.StatusInformation.displayName = 'proto.applibs.appcore.proto.StatusInformation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.applibs.appcore.proto.StatusItem.prototype.toObject = function(opt_includeInstance) {
  return proto.applibs.appcore.proto.StatusItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.applibs.appcore.proto.StatusItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    status: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    errorFlag: (f = jspb.Message.getBooleanField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.applibs.appcore.proto.StatusItem}
 */
proto.applibs.appcore.proto.StatusItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.applibs.appcore.proto.StatusItem;
  return proto.applibs.appcore.proto.StatusItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.applibs.appcore.proto.StatusItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.applibs.appcore.proto.StatusItem}
 */
proto.applibs.appcore.proto.StatusItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setErrorFlag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.applibs.appcore.proto.StatusItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.applibs.appcore.proto.StatusItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.applibs.appcore.proto.StatusItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string timestamp = 1;
 * @return {string}
 */
proto.applibs.appcore.proto.StatusItem.prototype.getTimestamp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.applibs.appcore.proto.StatusItem} returns this
 */
proto.applibs.appcore.proto.StatusItem.prototype.setTimestamp = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusItem} returns this
 */
proto.applibs.appcore.proto.StatusItem.prototype.clearTimestamp = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusItem.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string status = 2;
 * @return {string}
 */
proto.applibs.appcore.proto.StatusItem.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.applibs.appcore.proto.StatusItem} returns this
 */
proto.applibs.appcore.proto.StatusItem.prototype.setStatus = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusItem} returns this
 */
proto.applibs.appcore.proto.StatusItem.prototype.clearStatus = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusItem.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool error_flag = 3;
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusItem.prototype.getErrorFlag = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.applibs.appcore.proto.StatusItem} returns this
 */
proto.applibs.appcore.proto.StatusItem.prototype.setErrorFlag = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusItem} returns this
 */
proto.applibs.appcore.proto.StatusItem.prototype.clearErrorFlag = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusItem.prototype.hasErrorFlag = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.applibs.appcore.proto.StatusKey.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.applibs.appcore.proto.StatusKey.prototype.toObject = function(opt_includeInstance) {
  return proto.applibs.appcore.proto.StatusKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.applibs.appcore.proto.StatusKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    mainKey: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    subKey: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    statusList: jspb.Message.toObjectList(msg.getStatusList(),
    proto.applibs.appcore.proto.StatusItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.applibs.appcore.proto.StatusKey}
 */
proto.applibs.appcore.proto.StatusKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.applibs.appcore.proto.StatusKey;
  return proto.applibs.appcore.proto.StatusKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.applibs.appcore.proto.StatusKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.applibs.appcore.proto.StatusKey}
 */
proto.applibs.appcore.proto.StatusKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubKey(value);
      break;
    case 3:
      var value = new proto.applibs.appcore.proto.StatusItem;
      reader.readMessage(value,proto.applibs.appcore.proto.StatusItem.deserializeBinaryFromReader);
      msg.addStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.applibs.appcore.proto.StatusKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.applibs.appcore.proto.StatusKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.applibs.appcore.proto.StatusKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.applibs.appcore.proto.StatusItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string main_key = 1;
 * @return {string}
 */
proto.applibs.appcore.proto.StatusKey.prototype.getMainKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.applibs.appcore.proto.StatusKey} returns this
 */
proto.applibs.appcore.proto.StatusKey.prototype.setMainKey = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusKey} returns this
 */
proto.applibs.appcore.proto.StatusKey.prototype.clearMainKey = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusKey.prototype.hasMainKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string sub_key = 2;
 * @return {string}
 */
proto.applibs.appcore.proto.StatusKey.prototype.getSubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.applibs.appcore.proto.StatusKey} returns this
 */
proto.applibs.appcore.proto.StatusKey.prototype.setSubKey = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.applibs.appcore.proto.StatusKey} returns this
 */
proto.applibs.appcore.proto.StatusKey.prototype.clearSubKey = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.applibs.appcore.proto.StatusKey.prototype.hasSubKey = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated StatusItem status = 3;
 * @return {!Array<!proto.applibs.appcore.proto.StatusItem>}
 */
proto.applibs.appcore.proto.StatusKey.prototype.getStatusList = function() {
  return /** @type{!Array<!proto.applibs.appcore.proto.StatusItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.applibs.appcore.proto.StatusItem, 3));
};


/**
 * @param {!Array<!proto.applibs.appcore.proto.StatusItem>} value
 * @return {!proto.applibs.appcore.proto.StatusKey} returns this
*/
proto.applibs.appcore.proto.StatusKey.prototype.setStatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.applibs.appcore.proto.StatusItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.applibs.appcore.proto.StatusItem}
 */
proto.applibs.appcore.proto.StatusKey.prototype.addStatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.applibs.appcore.proto.StatusItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.applibs.appcore.proto.StatusKey} returns this
 */
proto.applibs.appcore.proto.StatusKey.prototype.clearStatusList = function() {
  return this.setStatusList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.applibs.appcore.proto.StatusInformation.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.applibs.appcore.proto.StatusInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.applibs.appcore.proto.StatusInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.applibs.appcore.proto.StatusInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
    recordList: jspb.Message.toObjectList(msg.getRecordList(),
    proto.applibs.appcore.proto.StatusKey.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.applibs.appcore.proto.StatusInformation}
 */
proto.applibs.appcore.proto.StatusInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.applibs.appcore.proto.StatusInformation;
  return proto.applibs.appcore.proto.StatusInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.applibs.appcore.proto.StatusInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.applibs.appcore.proto.StatusInformation}
 */
proto.applibs.appcore.proto.StatusInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.applibs.appcore.proto.StatusKey;
      reader.readMessage(value,proto.applibs.appcore.proto.StatusKey.deserializeBinaryFromReader);
      msg.addRecord(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.applibs.appcore.proto.StatusInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.applibs.appcore.proto.StatusInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.applibs.appcore.proto.StatusInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.applibs.appcore.proto.StatusInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecordList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.applibs.appcore.proto.StatusKey.serializeBinaryToWriter
    );
  }
};


/**
 * repeated StatusKey record = 1;
 * @return {!Array<!proto.applibs.appcore.proto.StatusKey>}
 */
proto.applibs.appcore.proto.StatusInformation.prototype.getRecordList = function() {
  return /** @type{!Array<!proto.applibs.appcore.proto.StatusKey>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.applibs.appcore.proto.StatusKey, 1));
};


/**
 * @param {!Array<!proto.applibs.appcore.proto.StatusKey>} value
 * @return {!proto.applibs.appcore.proto.StatusInformation} returns this
*/
proto.applibs.appcore.proto.StatusInformation.prototype.setRecordList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.applibs.appcore.proto.StatusKey=} opt_value
 * @param {number=} opt_index
 * @return {!proto.applibs.appcore.proto.StatusKey}
 */
proto.applibs.appcore.proto.StatusInformation.prototype.addRecord = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.applibs.appcore.proto.StatusKey, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.applibs.appcore.proto.StatusInformation} returns this
 */
proto.applibs.appcore.proto.StatusInformation.prototype.clearRecordList = function() {
  return this.setRecordList([]);
};


goog.object.extend(exports, proto.applibs.appcore.proto);
